import {
	Add01Icon,
	Alert02Icon,
	ArrowDown01Icon,
	ArrowLeft01Icon,
	ArrowRight01Icon,
	ArrowUp02Icon,
	BanIcon,
	BracketsIcon,
	Calendar01Icon,
	Cancel01Icon,
	CancelCircleIcon,
	CheckmarkCircle02Icon,
	ClaudeIcon,
	ComputerTerminal01Icon,
	Configuration01Icon,
	Copy01Icon,
	Delete02Icon,
	Download01Icon,
	FileCodeIcon,
	Home01Icon,
	InformationCircleIcon,
	Loading03Icon,
	MoreHorizontalIcon,
	PencilEdit01Icon,
	RefreshIcon,
	Search01Icon,
	Settings01Icon,
	Shield01Icon,
	SidebarLeft01Icon,
	StopIcon,
	ThumbsDownIcon,
	ThumbsUpIcon,
	Tick02Icon,
} from "@hugeicons/core-free-icons"
import {
	HugeiconsIcon,
	type HugeiconsIconProps,
	type IconSvgElement,
} from "@hugeicons/react"

type IconProps = Omit<HugeiconsIconProps, "icon">

const createIcon = (icon: IconSvgElement) => {
	const Icon = (props: IconProps) => <HugeiconsIcon icon={icon} {...props} />
	return Icon
}

const Icons = {
	Add: createIcon(Add01Icon),
	Alert: createIcon(Alert02Icon),
	ArrowDown: createIcon(ArrowDown01Icon),
	ArrowLeft: createIcon(ArrowLeft01Icon),
	ArrowRight: createIcon(ArrowRight01Icon),
	Blocked: createIcon(BanIcon),
	Calendar: createIcon(Calendar01Icon),
	Check: createIcon(Tick02Icon),
	Claude: createIcon(ClaudeIcon),
	Close: createIcon(Cancel01Icon),
	Copy: createIcon(Copy01Icon),
	Delete: createIcon(Delete02Icon),
	Download: createIcon(Download01Icon),
	Edit: createIcon(PencilEdit01Icon),
	Error: createIcon(CancelCircleIcon),
	FileCode: createIcon(FileCodeIcon),
	Home: createIcon(Home01Icon),
	Info: createIcon(InformationCircleIcon),
	Json: createIcon(BracketsIcon),
	Loading: createIcon(Loading03Icon),
	More: createIcon(MoreHorizontalIcon),
	Retry: createIcon(RefreshIcon),
	Search: createIcon(Search01Icon),
	Send: createIcon(ArrowUp02Icon),
	Settings: createIcon(Settings01Icon),
	Shield: createIcon(Shield01Icon),
	Sidebar: createIcon(SidebarLeft01Icon),
	Stop: createIcon(StopIcon),
	Success: createIcon(CheckmarkCircle02Icon),
	Terminal: createIcon(ComputerTerminal01Icon),
	ThumbsDown: createIcon(ThumbsDownIcon),
	ThumbsUp: createIcon(ThumbsUpIcon),
	Tool: createIcon(Configuration01Icon),
}

export { type IconProps, Icons }
